name: Deploy to WordPress.org
on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Prevent upload to wordpress.org (Dry Run)"
        default: true
        type: boolean

jobs:
  tag:
    name: New release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Mark github workspace as safe
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Build
        run: composer build
        env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ADD_TO_PROJECTS_PAT }}"}}'

      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        with:
          generate-zip: true
          dry-run: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run }}
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: gf-entries-in-excel
          ASSETS_DIR: assets
      - name: Upload release asset
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.deploy.outputs.zip-path }}
